services:
  logic-ecom-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logic-ecom-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://life-organizer-db:5432/life_organizer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: your_password
    networks:
      - life-shared-network
    restart: unless-stopped

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiNGEwNDc3MGMwMDcwMTA0ZjQzY2YyN2NlNDZiYzAyMGMiLCJ0IjoiNGNkNjZkM2ItMjllZC00MjVjLWE5ZTctN2I1YzVjMWJmZTQzIiwicyI6Ik9UUTFOREptTTJZdFltVmhOaTAwWTJWaUxXRmtOVE10WVdNMll6ZG1aV05qT1RNMyJ9
    networks:
      - life-shared-network

networks:
  life-shared-network:
    external: true