spring.application.name=eddie

#server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5433/life_organizer
spring.datasource.username=root
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=ZmFrZS1zdXBlci1sb25nLXNlY3JldC1rZXktdXNlLWEtYmFzZTY0LWtleS1vci1hLWZ1bGwtMjU2Yml0LXN0cmluZw==
jwt.expiration-ms=36000000

spring.profiles.active=dev
#spring.aop.proxy-target-class=true

spring.liquibase.change-log=classpath:db/master.yaml

cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS

logging.level.org.springframework.security=DEBUG

# More web diagnostics
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# Return detailed error payloads
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=true
server.error.include-stacktrace=always

# Make 404 raise an exception (so it?s logged and handled below)
spring.web.resources.add-mappings=false
