package life_ecom_logic_core.eddie.domain;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcType;
import org.hibernate.dialect.PostgreSQLEnumJdbcType;

import java.time.OffsetDateTime;

/**
 * JPA entity for the notifications table.
 * Notifications are created automatically by process_recurring_transactions()
 * or manually for payment reminders and system events.
 */
@Entity
@Table(name = "notifications")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class NotificationEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", columnDefinition = "uuid", nullable = false)
    private UserEntity user;

    /** Present when generated by a recurring rule; null for system/manual notifications. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "recurring_transaction_id")
    private RecurringTransactionEntity recurringTransaction;

    /** Related transaction, if any. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "transaction_id")
    private TransactionEntity transaction;

    /** Related goal — set for goal reminder notifications. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "plan_id")
    private FuturePlanEntity plan;

    @Enumerated(EnumType.STRING)
    @JdbcType(PostgreSQLEnumJdbcType.class)
    @Column(name = "type", columnDefinition = "notification_type", nullable = false)
    private NotificationTypeEnum type;

    @Column(name = "title", nullable = false)
    private String title;

    @Column(name = "message", nullable = false)
    private String message;

    /** When the notification should be surfaced to the user. */
    @Column(name = "scheduled_for", nullable = false)
    private OffsetDateTime scheduledFor;

    /** Null until the notification is delivered/read. */
    @Column(name = "sent_at")
    private OffsetDateTime sentAt;

    /** Field named 'read' so Lombok generates isRead() correctly. Maps to is_read column. */
    @Column(name = "is_read", nullable = false)
    private boolean read;

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;
}
